### ISSUE TITLE
Mobile UI: Hamburger draw covers entire screen on some handsets

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#113]
The layout of the hamburger draw does not respond to smaller screen sizes. On small screens (e.g. Samsung Galaxy S5) it covers the entire screen. The user must rotate the device and tap outside the draw to retract the drawer.

![image](https://cloud.githubusercontent.com/assets/329768/16999855/1031c5ca-4e8e-11e6-968b-23af89d70627.png)

**Comment by scloo** [comment]
The drawer will now retract itself when an option is selected. This is the same for all screen sizes.
