### ISSUE TITLE
Mobile UI: Style hamburger draw menu

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#114]
Restyle the hamburger draw menu so icons are consistent between mobile and analytics apps. See #51 for making this menu responsive for smaller screen sizes.

![image](https://cloud.githubusercontent.com/assets/329768/17000003/aac688c8-4e8e-11e6-8866-dd8832a7d3d5.png)

**Comment by scloo** [comment]
Issue has been addressed
