### ISSUE TITLE
Mobile UI: Redesign app install display

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#116]
This issue consolidates multiple issues, which will be closed.

![image](https://cloud.githubusercontent.com/assets/329768/17001150/cefad776-4e93-11e6-9864-c01c1600189b.png)
- [x] Resign display to respond to small displays
- [x] Add Support and About to dot menu in upper right. Look at Analytics menu, and determine what else belongs on this menu.
- [x] Determine what belongs in the hamburger drawer.

**Comment by scloo** [comment]
Issues addressed
