### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#118]
Using correct password, but unable to log in. Not sure what caused this, or how to correct it. I wonder whether we need an option to uninstall the app, with appropriate warnings, to resolve such a situation.
![image](https://cloud.githubusercontent.com/assets/329768/17001703/27dd9d9a-4e96-11e6-82d2-fba29452c86c.png)

**Comment by scloo** [comment]
This should be fixed. Able to log in fine with this user name and password.
