### ISSUE TITLE
Mobile UI: General redesign

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#119]
Current nav strip does is not responsive to smaller displays. Text overlaps text. Text spills off page. Sync icon overlaps text. 

Each item in the nav strip is a question set. The number of incomplete records in each question set is indicated by a badge. Each question set could be symbolized by an icon that matches icons used throughout the mobile app and analytics. 

![image](https://cloud.githubusercontent.com/assets/329768/17022102/0cd5e5e6-4f1a-11e6-9c2a-6f35f4285c9e.png)

![image](https://cloud.githubusercontent.com/assets/329768/17022107/10ca383c-4f1a-11e6-924a-f667f79c15e0.png)

Question sets are also listed on the hamburger menu.

The hamburger menu covers the display completely in portrait orientation.

![image](https://cloud.githubusercontent.com/assets/329768/17022129/2a634112-4f1a-11e6-889d-4483e44ea6cb.png)

The user must rotate the device and click outside the menu to retract the hamburger menu drawer. This is also listed in a separate issue.

![image](https://cloud.githubusercontent.com/assets/329768/17022151/4391c3b6-4f1a-11e6-9d29-497cd256be21.png)

The information displayed for each question set includes summary statistics and a table of records that need to be completed. The number of records in the table should match the number in the badge for the question set. The user scrolls down to view all of the information.

![image](https://cloud.githubusercontent.com/assets/329768/17022194/937dd8c4-4f1a-11e6-906b-196f5b5e06eb.png)

![image](https://cloud.githubusercontent.com/assets/329768/17022198/9805a296-4f1a-11e6-8f40-a9aa97767acb.png)

![image](https://cloud.githubusercontent.com/assets/329768/17022201/9b4e7c16-4f1a-11e6-9454-26de7e3a9e82.png)

And in portrait orientation:

![image](https://cloud.githubusercontent.com/assets/329768/17022245/dacade2a-4f1a-11e6-912f-363328d4439f.png)

![image](https://cloud.githubusercontent.com/assets/329768/17022247/df64c9c8-4f1a-11e6-856f-44923a75bfec.png)

**Comment by scloo** [comment]
I believe all the above issues have been resolved. But if there is any that wasn't please create a new ticket.
