### ISSUE TITLE
Unable to install zanzibar

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#125]
Using latest Chrome on OS X El Capitan.

![image](https://cloud.githubusercontent.com/assets/329768/17816379/dd247732-6606-11e6-8106-2f7fdb1455c0.png)

**Comment by mikeymckay** [comment]
Please try again - I made some updates today.

**Comment by gmcressman** [comment]
Cleared all cococloud.co app data and tried again. Still failing on me.

**Comment by mikeymckay** [comment]
Same error?

**Comment by gmcressman** [comment]
Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/329768/18438929/57447b16-78d1-11e6-8f63-0048142473d0.png)

**Comment by gmcressman** [comment]
I have been able to install zanzibar. We still need to test installing, using, and uninstalling multiple coconut apps on the same device. We have several use cases to test for this. Closing this issue.
