### ISSUE TITLE
Not loading plugins

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#127]
Console shows error below. Suspect that the plugins are not loading for some reason.

Uncaught (in promise) ReferenceError: FacilityHierarchy is not defined
  at eval (<anonymous>:1:26)
  at http://localhost:8089/bundle.js:2733:15
  at Function._.each._.forEach (http://localhost:8089/bundle.js:94119:9)
  at QuestionView.render (http://localhost:8089/bundle.js:2731:7)
  at QuestionView.render (http://localhost:8089/bundle.js:2541:57)
  at success (http://localhost:8089/bundle.js:741:38)
  at Object.options.success (http://localhost:8089/bundle.js:7452:30)
  at callback (http://localhost:8089/bundle.js:6742:43)
  at http://localhost:8089/bundle.js:87291:7

**Comment by scloo** [comment]
In Coconut.coffee, we have the following codes:

syncPlugins: (options) =>
    $("#status").html "Checking for available plugins"
    @cloudDB = @cloudDB or new PouchDB(@config.cloud_url_with_credentials())
    @cloudDB.allDocs
      include_docs:false
      startkey: "_design/plugin-#{@databaseName}"
      endkey: "_design/plugin-#{@databaseName}\ufff0" #https://wiki.apache.org/couchdb/View_collation
    .then (result) =>


I noticed in the startkey and endkey we have  "_design/plugin-#{@databaseName}"
Which translates to "_design/plugin-coconut-surveillance-zanzibar". Is this correct? 
In the coconut-surveillance-zanzibar DB, there is no such design doc but "_design/plugin-zanzibar".  

The original database was "zanzibar" in which case "_design/plugin-#{@databaseName}" will be translated correctly to "_design/plugin-zanzibar" which exists. You have copied the original zanzibar DB to coconut-surveillance-zanzibar DB, should this design doc not be renamed to "_design/plugin-coconut-surveillance-zanzibar" ?

I think this is the reason why "result.row.length"  is always zero. And hence no plugins loaded.

**Comment by mikeymckay** [comment]
Yes that's correct - I renamed the database, so the plugin needs to be
renamed too. Having something just named Zanzibar seemed like a bad idea.
:-)

**Comment by scloo** [comment]
Even though after the correction in the plugin name and successfully found the plugin, it still have problem loading/eval the plugin. 
Error shows:
  Error loading _design/plugin-coconut-surveillance-zanzibar
  TypeError: Cannot read property 'organisationUnits' of undefined

Actual code where error encountered:

function GeoHierarchy(rawData) {
    this.rawData = rawData;    
    .....

    this.units = _(this.rawData.organisationUnits).map(function(rawUnit) {
       return new Unit(rawUnit);
    });
}

**Comment by scloo** [comment]
Issue fixed. The repository did not have the latest codes pushed.
