### ISSUE TITLE
Installing coconut project crash

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#128]
When installing a new coconut project, if the project already exist and you proceed to delete it, after 'successfully' deleted the project and proceeding to install. The installation will hang and spinner goes on forever. However if I delete the storage databases in the cookies, it will install successfully.
Apparently destroying the project does not delete the storage/indexed databases in the cookies, for some reason.

**Comment by mikeymckay** [comment]
There is a pouchdb plugin called allDbs - which is used to track all of the databases that are available for the URL. I have found some problems with it when deleting and reinstalling.

This is the line that enables the plugin:
require('pouchdb-all-dbs')(window.PouchDB)

And you can use PouchDB's debug mode to see what happens. This is how I found that allDBs was breaking:
PouchDB.debug.enable('*')

(note that debug mode will stay on until you .disable() it)

**Comment by scloo** [comment]
I wonder why the debug is showing everything twice.

pouchdb:api coconut-coconut-surveillance-zanzibar-user.0773126786 +9ms get success Object {_id: "_local/crypto", salt: "4f53698acb4ae4ddeecf234a7148ef62", _rev: "0-1"}
pouchdb:api coconut-coconut-surveillance-zanzibar-user.0773126786 +2ms get success Object {_id: "_local/crypto", salt: "4f53698acb4ae4ddeecf234a7148ef62", _rev: "0-1"}

pouchdb:api coconut-coconut-surveillance-zanzibar-user.0773126786 +1ms get success Object {_id: "_local/crypto", salt: "4f53698acb4ae4ddeecf234a7148ef62", _rev: "0-1"}
pouchdb:api coconut-coconut-surveillance-zanzibar-user.0773126786 +1ms get success Object {_id: "_local/crypto", salt: "4f53698acb4ae4ddeecf234a7148ef62", _rev: "0-1"}

pouchdb:api coconut-coconut-surveillance-zanzibar-user.0773126786 +107ms get decryption check Object {}
pouchdb:api coconut-coconut-surveillance-zanzibar-user.0773126786 +167ms get decryption check Object {}

pouchdb:api pouch__all_dbs__ +8ms get success Object {_id: "db_coconut-coconut-surveillance-zanzibar-user.0773126786", _rev: "1-5ff2fcf092d46636e2270adade977da9"}
pouchdb:api pouch__all_dbs__ +3ms get success Object {_id: "db_coconut-coconut-surveillance-zanzibar-user.0773126786", _rev: "1-5ff2fcf092d46636e2270adade977da9"}

pouchdb:api pouch__all_dbs__ +5ms get db_coconut-coconut-surveillance-zanzibar-user.0773126786
pouchdb:api pouch__all_dbs__ +1ms get db_coconut-coconut-surveillance-zanzibar-user.0773126786

**Comment by scloo** [comment]
Duplicate with issue#130
