### ISSUE TITLE
Use Results display as default display?

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#13]
The Results display, which has not yet been given the MD treatment, has an "Add new visit" link at the top. This is redundant, since that appears in the form action menu at the top. This suggests that the Results display could be the default display whenever a form is not displayed. This would give the user information immediately after log in on incomplete records and records already synched. Just a thought.

**Comment by mikeymckay** [comment]
I like the idea. Only problem is that in case of multiple question sets I guess it would just choose the first one. I guess that's ok.

**Comment by gmcressman** [comment]
Agreed - makes no sense with more than one question set. Forget it. Go to bed and get some sleep.

**Comment by gmcressman** [comment]
Deprecated. We've moved on. Closing.
