### ISSUE TITLE
App install fails with ugly error for invalid Cloud URL

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#132]
Entered "adfasdd" for Cloud URL. Need better validation of cloud URL, and better error message. Should not start install unless Cloud URL is valid.

![cococloud co-coconut-mobile2-_design-couchapp-index html galaxy s5 2](https://cloud.githubusercontent.com/assets/329768/24921377/9d2ba400-1eb8-11e7-9f8a-74ccb561765d.png)

**Comment by scloo** [comment]
Changes made.
