### ISSUE TITLE
Design sync status display

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#14]
The detailed information displayed when syncing data is great, but is probably not meaningful to most users. In fact, it might scare them. Design a simple sync status display that indicates to them:

- Whether the app connected to the remote database
- How many records need to be synced
- How many have been synced and how many remain to be synced
- Whether the app finished syc successfully

A simple graphic status progress indicator with a simple text status message might work.

Find a way for technical support personnel to also reveal the detailed technical status messages.

**Comment by scloo** [comment]
I noticed that on mobile.cococloud.co during syncing it display the status details but at the end of the detail it says "Please wait". Even though I believe the syncing has completed (I think). Can be confusing to users. Perhaps for now better to display "Syncing completed" when it is done.

**Comment by mikeymckay** [comment]
Spinner added with simple messages, debug hidden unless error.

**Comment by gmcressman** [comment]
This new sync status display is excellent!

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>
