### ISSUE TITLE
Delete Application bug

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#140]
When deleting an application, it takes 2 or more  attempts before the application is deleted.

**Comment by scloo** [comment]
The strange part of this issue is that it only happens on cococloud.co but not on localhost.

**Comment by scloo** [comment]
On further investigation, it seems like pochDB .destroy() is not deleting all the databases each time. And because of this, it causes issue like after running Delete Application, it still say already exists and needed to be deleted again. And this also causes the problem highlighted in issue# 139

**Comment by gmcressman** [comment]
There may be useful information here: https://github.com/pouchdb/pouchdb/issues/4135

That seemed to be the closest to me, searching in the PouchDB repo: https://github.com/pouchdb/pouchdb/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20destroy
