### ISSUE TITLE
Coconut.config location

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#143]
In coconut mobile, when we read the coconut config file for the values, where does this doc reside? I am assuming that it is in the browser database rather than on the cloud database.

If  I'm not mistaken, when we first create the application, Coconut Mobile pulls the config from the cloud server to the browser. Subsequent get action will get it from the browser database. Is that correct?

**Comment by gmcressman** [comment]
Wouldn't moving this, or at least some if it, to the database solve this? Then updated values would be picked up during sync.

**Comment by scloo** [comment]
Confirmed that the settings will also be sync'ed to the local database during the sync process.
