### ISSUE TITLE
Skipping workflow in setup process?

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#147]
During the setup we first fill up the setup form, and if the application already exist, it will ask to proceed to delete the application. After deletion, it shows the setup form again, in which case, we have to click Install button. Wouldn't it simplify the process to skip displaying the form a second time and just proceed to creating the databases and documents, after completing the deletion?

**Comment by gmcressman** [comment]
I agree with you. We shouldn’t prompt the user again for information entered already.

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by scloo** [comment]
Refactored codes to go straight to installing after removing old application.
