### ISSUE TITLE
Coconut.coffee:182 Error loading _design/plugin-coconut-surveillance-zanzibar

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#148]
During login, gives error message of invalid username or password, even though correct.

How to replicate: 
1. in Select a Coconut Application, click install a new one.
2. Proceed to recreate coconut-surveillance-zanzibar.
3. Delete existing database.
4. Continue creating databases.
5. Once completed, get a login screen. Cancel login to go back to Select a Coconut Application screen.
6. Click the application to get a login screen.
7. Attempting to login now will throw the error.

To overcome this error, reload the page.

**Comment by gmcressman** [comment]
I also encountered this problem this morning.

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by scloo** [comment]
Bug fixed.
