### ISSUE TITLE
Investigate why there are cases for 2018

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#150]
These 2018 dates are found in the anonymized  Coconut-surveillance-zanzibar database.

**Comment by scloo** [comment]
At the moment, during the anonymizing process, the dates are shifted by a specified number of days, currently 430. My guess was that dates that were originally in 2017 were shifted to 2018. However I was not able to find the corresponding doc in the unanonymized database that correspond to the 2018 doc in the anonymized database.

**Comment by scloo** [comment]
I think the 2018 dates cases were probably from the test run of the anonymizing process before the script was finalized. From what I can tell from the script, any cases beyond 2016 will be removed before anonymizing and dates shifting. And I think the script has not ran since. From what I can tell, there is no cronjob for this. So I think at the next running of the script, the 2018 dates should disappear.

**Comment by gmcressman** [comment]
Actual data from 2015 looks good. Performance deteriorated in 2016. I also believe that we do not have a complete year of data from 2016. We should pick the last month of actual data (say, December 2015), and delete all of the records after that. This should give us a better-looking demo data set. We can then anonymize that and continue to advance the dates to make the data appear to be current.

**Comment by scloo** [comment]
Sorry I misread the script. It is deleting data after 2016-01-01 and before 2012-12-31

**Comment by scloo** [comment]
I tried running the anonymize.rb script. But it gave unexpected results. There was only one record resulting from the caseIDsByDate view,  after running the anonymize script. 
Also notice in the anonymize.rb script, there was references to view 'zanzibar/caseIDsByDate' instead of 'caseIDsByDate/caseIDsByDate'. Would that be a mistake in the naming?

**Comment by gmcressman** [comment]
Adding to this, we need to make sure that the demo data contains a realistic set of case notifications from the facilities, to which demo users could respond. These can be created in the demo data. We should make sure that the two demomobile[1|2] accounts are assigned to districts that have case notifications.

**Comment by scloo** [comment]
Closing this ticket as it is related to #318
