### ISSUE TITLE
Verify the Sync data in the database

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#151]
Verify that the Sync'ed data is in the Analytics reports

**Comment by scloo** [comment]
Data is sync'ed to the server couchDB database. But after sync'ed , the _id is something like "dde07ec3-e421-4982-a97a-ad798162d8e1". However the couchDB view that was used to pull up the data for the Analytic reports (caseIDsByDate), the search condition is 
if doc._id.lastIndexOf("case_summary_", 0)

This will fail for the new records that was sync'ed because its _id is not prefixed with case_summary_

@mikeymckay is this a bug?

**Comment by scloo** [comment]
Another question - what is the reason for not having an autogenerated Malaria caseID , instead of user keying?  For example case_summary_xxxxxxx   where xxxxxxx is autogenerated.  If user defined, we ended up with all sorts of ID in the data.

**Comment by scloo** [comment]
The more I dig into the database, the more confused I become. There are different ID formats. Some as case_summary_xxxxxx, while others are long like "8c7943046921d82ac012bbc1d8000c29". 

The question remains that the Analytics Followup report, it is expecting case_summary_xxxxxx format because it is using the CaseIDsByDate/CaseIDsByDate view to pull out the docs, and not the zanzibar/CaseIDsByDate view. 

I'm sure there is a simple explanation to all this.

**Comment by scloo** [comment]
Mike pointed out that the case_summary_xxxx docs are for the tertiary index. And so CaseIDsByDate/CaseIDsByDate  view is being correctly used in Analytics. 

The  tertiary index is being updated in the background in a cron job periodically. And hence the data sync may not show up instantly in the Analytics  report.

**Comment by scloo** [comment]
Looks like the sync process is not working.

Background sync log shows (when there is one newly created completed Case Notification and a Facility record.) :

backgroundSync called at Wed May 17 2017 15:21:25 GMT-0400 lastSuccessfulSync was Wed May 17 2017 15:11:26 GMT-0400}
Initiating background sync
No new results for Facility so not syncing
 Checking for internet. (Is http://localhost:5984/coconut-surveillance-zanzibar is reachable?) Please wait.
http://localhost:5984/coconut-surveillance-zanzibar is reachable, so internet is available.
Creating list of all results on the mobile device. Please wait.
No new results for Household so not syncing
No new results for Household Members so not syncing
Synchronizing 5 results. Please wait.
Success! Send data finished: created, updated or deleted 1 results on the server.

I had the UpdateCaseSummaryDocs.coffee script running on the terminal and the console log showed:
{ _id: 'CaseSummaryData',
  _rev: '353-8620b8856de9b43459b038f36373a8df',
  lastChangeSequenceProcessed: 1299731 }
{ results: [], last_seq: 1056301 }
Looking for the next 500 changes after 1299731
Changed cases: 
Updated 0 cases, lastChangeSequence: 1299731
Number of cases changed: 0
DONE


I was expecting to see "Updated 1 cases" or "Number of cases changed: 1". But instead it showed zero. And I can't seem to find the record on couchDB either.

**Comment by gmcressman** [comment]
I tested background sync in Chrome (MacBook Pro) and Nexus 7 tablet yesterday. The console in Chrome showed that it was working. I’ll look further.

**Comment by scloo** [comment]
The background sync is running as set. And according to the console log, it  was sending to the server:
"Synchronizing 6 results. Please wait.
Coconut.coffee:41 Success! Send data finished: created, updated or deleted 1 results on the server."

But the problem is the records could not be found.

**Comment by gmcressman** [comment]
What could possibly have changed to affect synchronization?

**Comment by scloo** [comment]
@mikeymckay 
For the codes below in Case.updateCaseSummaryDocsSince, the 'result' return is always empty:

    Coconut.database.changes
      live: false
      since: options.changeSequence
      include_docs: true
      limit: limit
    .then (result) ->

Hence it is not updating the CaseSummaryDocs. Are you able to see the cause of the empty "result" from the above codes?

**Comment by scloo** [comment]
Issue resolved.Solution:
1. Run the ResetCaseSummaryDocs script
2. Kill the process for UpdateCaseSummaryDocs that ran from cron job. And rerun the command: 
/usr/local/bin/forever start -c /var/www/coconut-analytics/_attachments/node_modules/coffee-script/bin/coffee /var/www/coconut-analytics/_attachments/app/UpdateCaseSummaryDocs.coffee https://cococloud.co/coconut-surveillance-zanzibar

For some reason the process for UpdateCaseSummaryDocs was not working and needed to be restarted.
Now any new Case in mobile that is sync will now appear in the Analytics Case Followup status report.

**Comment by gmcressman** [comment]
This is fantastic Steve. I'll test this as soon as I can today.

**Comment by gmcressman** [comment]
Done.
