### ISSUE TITLE
Restore coconut surveillance workflow

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#152]
In the coconut surveillance plug-in:
1. Receiving a new cast notification (Case Notification Sent) should create a matching (not Complete) Case Notification Received record.
2. Completing a Case Notification Received record should create a matching (not Complete) Facility record.
3. Completing a Facility record should create a matching (not Complete) Household record.
4. Completing a Household record should generate the correct number of (not Complete) Household Members records.

This functionality should be in the coconut surveillance plug-in. Something has disabled this important functionality.

**Comment by scloo** [comment]
The functionality is in the plugin. But it is not being called from anywhere. Mike maybe able to  throw some light on this whether it is not implemented yet or just an oversight.

**Comment by gmcressman** [comment]
Mike confirmed to me this morning that this functionality was in the plug-in and was working before. Can you see any reason why this is not being triggered in the code we have now?

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by scloo** [comment]
I have never seen this functionality in action before. Initially we were unable to load the plugin. But that is now fixed and I still did not see this functionality acting. If it was broken, there should be a message in the console. But there is none related.

The codes are in the plugin as a function known as Case.createNextResult but I could not find reference to this function anywhere in the Mobile codes. I checked in the git log on the changes I have committed and I could not find this either.

**Comment by scloo** [comment]
On further investigation, the function  createNextResult in the plugin doesn't seem to be the function for the job. 
Rather it is a predefined sets of Coffeescript instructions supposedly stored in the Question model, and it is called onValidatedComplete. However I have not yet found where this is being populated into the Question model. Currently it is not doing anything simply because this set of instructions is not in the Question model.

**Comment by gmcressman** [comment]
Is it in the question set documents?

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by scloo** [comment]
Yes, it is supposed to be in there. Anyhow I have found the reason why they are missing. When Mike duplicated the original database 'zanzibar', for some reason it was not replicated there in the new database coconut-surveillance-zanzibar and hence missing.

I have just created the missing field onValidatedComplete.

**Comment by scloo** [comment]
@mikeymckay  I wonder when you were running the anonymize script, was the attribute 'onValidatedComplete.' left out by any chance?

**Comment by scloo** [comment]
New errors now when loading up the QuestionView form:

No caseID to fetch data for
	Case.fetch	@	VM5604:172
(anonymous)	@	VM5604:3
Case.createNextResult	@	VM5604:771
(anonymous)	@	VM5604:3
(anonymous)	@	coffeescript [sm]:1
CoffeeScript.eval	@	coffee-script.js:12
(anonymous)	@	bundle.js:3
(anonymous)	@	bundle.js:47

The Coffeescript that was executing upon action_on_questions_loaded :
window.malariaCase = new Case({caseID: Coconut.questionView.result.get 'MalariaCaseID'}); malariaCase.fetch();

And apparently Coconut.questionView.result does not contain MalariaCaseID. And hence subsequent fetch statement failed.

**Comment by scloo** [comment]
Aha!!  Almost working now. When you completed the Case Notification, it will auto create a Facility question. But still very buggy. Only work if you do things in a specific order.

The error message mentioned earlier is still there but that is because when you create a new Case Notification, there is no caseID yet, because the MalariaCaseID at that point is blank. Will open another ticket for that.

**Comment by scloo** [comment]
What's working: - if you create a incomplete Case Notification, and return to the Case Notification result view, and the select the question to edit. Then mark Complete. This will auto create a Facility doc.

What's not working: Create a new Case Notification, and mark complete at the same time. This will not create a Facility. Instead we will get a console message "No caseID to fetch data for"

**Comment by scloo** [comment]
Problem fixed.

**Comment by gmcressman** [comment]
Done.
