### ISSUE TITLE
Household question set: Household Location: font size too large

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#153]
Samsung Galaxy S5
Vertical orientation

![image](https://cloud.githubusercontent.com/assets/329768/25915986/2f820fee-3591-11e7-89d4-3aeaa5f8036d.png)

**Comment by scloo** [comment]
Fixed

**Comment by gmcressman** [comment]
I don't see any change. This shouldn't require a delete and reinstall, should it?

**Comment by scloo** [comment]
A screen reload should do it.
