### ISSUE TITLE
Hamburger Menu: Reset database still relevant?

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#156]
Do we will need the "Reset database" function in the hamburger menu? If so, should this appear only for the Admin role.

**Comment by mikeymckay** [comment]
If something goes wrong the user needs to be able to reset their database and startover. It needs to be available to the user, but it could be hidden.

**Comment by gmcressman** [comment]
We could move that to the Manage menu.

**Comment by scloo** [comment]
I noticed that the Reset Database option is in essence  deleting the database app. If that is the case, we don't really require that any more since we are able to do the same at the "Select a Coconut Application" view by clicking the delete icon for the appropriate app.

**Comment by scloo** [comment]
This has been removed from the hamburger menu. No longer need this since this is handles in the Application Selection view.
