### ISSUE TITLE
Change icon for household

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#158]
![image](https://cloud.githubusercontent.com/assets/329768/26056900/37c5574e-3945-11e7-9686-66e34909d34e.png)

![image](https://cloud.githubusercontent.com/assets/329768/26056903/3c140ae8-3945-11e7-9281-1ade19adb556.png)

![image](https://cloud.githubusercontent.com/assets/329768/26056906/404c6736-3945-11e7-8ff0-e601ca887d5d.png)

**Comment by scloo** [comment]
Done
