### ISSUE TITLE
Facility hierarchy not defined

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#159]
![image](https://cloud.githubusercontent.com/assets/329768/26057318/2401e7fc-3947-11e7-9125-bb4e1b635af5.png)

**Comment by scloo** [comment]
For some  reason, the field "isApplicationDoc" keeps disappearing from the dhis2 doc in couchdb. I added it in the last time. And then it disappeared, which causing this error and breaking.

**Comment by scloo** [comment]
Fixed
