### ISSUE TITLE
SummaryView undefined on start of Mobile

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#160]
Upon loading of Mobile app, even after the successful loading of the plugin, the Coconut.summaryView is undefined.

Hence invoking the navigate does not work.
Coconut.router.navigate "##{Coconut.databaseName}/summary", trigger:true

However if I click on any other menu links (except for sync) first and then click the Home icon, then it will work from then on. Until re-login.

**Comment by scloo** [comment]
Problem fixed. Apparently the plugin is not known until the Backbone history is reloaded using Backbone.history.loadUrl() command. Hence whenever a plugin cannot be found,  a Backbone history is required to bring the history up to date.

This also resolved the failure to load the SummaryView upon login or initial page loading.

**Comment by gmcressman** [comment]
Fixed.
