### ISSUE TITLE
Convert password verification

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#162]
Convert password verification in Mobile to use hash password.

**Comment by scloo** [comment]
The current verification setup on Mobile breaks down when we switch to using hashed Password. We want to avoid storing plain-text password in the user doc. Hence we hash the password and store as hash.

In the mobile, during setting up Application, the database is sync to the local browser, and then encrypted using the password in the user doc. (from couchDB server). If that password is in the hash format, then crypto-pouch will encrypt databases using this hashed password. During the user login on mobile, it will not be possible to verify the password because the local user doc is in the encrypted database. Hence the chicken and egg situation.

**Comment by scloo** [comment]
Hash password can be reproduced using the predefined salt. Hence during login the hashkey is produced using the user login password and predefined salt, and then using this to decrypt the local browser database.

**Comment by scloo** [comment]
Due to this change, you need to recreate the Application, in order to download the updated database. Otherwise login will fail due to previous old non-hash password.

**Comment by gmcressman** [comment]
Leaving this open pending resolution of #180

**Comment by gmcressman** [comment]
Done!
