### ISSUE TITLE
Change "Tablet" to "Device"

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#164]
![image](https://cloud.githubusercontent.com/assets/329768/26798935/90053070-4a00-11e7-94a4-31a18a2bce01.png)

**Comment by gmcressman** [comment]
- [ ] Check code for any other instances of "tablet". Change any instances to "device".

**Comment by scloo** [comment]
Fixed

**Comment by gmcressman** [comment]
Done.
