### ISSUE TITLE
Resign transfer confirmation display

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#166]
The case transfer confirmation display currently displays the JSON for each record to be transferred. All records with the same Malaria Case ID are transferred. The purpose of the display is to inform the user which records will be transferred. Redesign this display using MD.

![image](https://user-images.githubusercontent.com/329768/26849750-4f949f98-4ad3-11e7-9c97-98c2e5994f90.png)

**Comment by scloo** [comment]
What essential details need to show up in the table format?

**Comment by gmcressman** [comment]
I think the user needs a table showing the following:
Malaria Case ID (same for all records in the table) | Question Set (?) [Case Notification | Facility | Household Member ] | Complete [Yes | No]

This table would contain one or more records. Each record will have the same Malaria Case ID.

**Comment by scloo** [comment]
Display as table now.

**Comment by gmcressman** [comment]
Fixed. Posting a new issue to improve this UI.
