### ISSUE TITLE
Improve handling of sync when there is no Internet connection

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#172]
When there is no internet connection, Sync displays ugly error messages below the spinner and appears to hang. We need to do a much nicer job of detecting that there is no internet connection, providing that feedback to the user via MD guidelines, and returning control to the user.

![image](https://user-images.githubusercontent.com/329768/27033873-3c877cfc-4f49-11e7-8dc4-d61c604b6b6c.png)

**Comment by scloo** [comment]
Done

**Comment by gmcressman** [comment]
Checked.
