### ISSUE TITLE
Weird icons or missing icons on header

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#174]
On a mobile device, after going offline and restarting app by clicking home screen icon, the app header icons either appear as weird icons (chinese characters) or are missing from the header.
This problem only affects offline mode.

**Comment by scloo** [comment]
The developer console shows the following error message.
   Failed to decode downloaded font: **name of font**
   OTS parsing error: invalid version tag

We are using the material design icons that includes community icons added to Google icons.
https://materialdesignicons.com

Solution:
In the css/materialdesignicons.min.css file where the definition for the font-face for each of the fonts, need to remove the version tag "?v=1.9.31" from the url. This is a hack to make the browser skip the version tag checking. Do not know if this is a bug in the html5 manifest feature that it was unable to interpret this version tag.

This hack may be broken when upgrading the material design icons files in the future if this change is overwritten. As it is, there is no other known solution or fix at the moment.

In order for this hack to take effect on the mobile device, you must reinstall the application after deleting the home icon and the cookies. (In the browser Settings -> Site settings -> Storage. Delete anything that has "mobile.cococloud.co" in it.)

**Comment by gmcressman** [comment]
Nice work @scloo. I'll test as soon as I can.

**Comment by gmcressman** [comment]
Fixed.
