### ISSUE TITLE
Adjust login to small displays in landscape mode

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#178]
Can the login panel adjust to small displays in landscape mode, so that all controls can be seen without scrolling vertically?

![image](https://user-images.githubusercontent.com/329768/27589602-0267cfa4-5b1a-11e7-96d5-96f639c1b6bc.png)

**Comment by scloo** [comment]
Updated to fit as much as possible in landscape mode in mobile devices.

**Comment by gmcressman** [comment]
Perfect. Done.
