### ISSUE TITLE
Summary view not reflecting latest changes

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#181]
When you make a change in the Question views, e.g. Adding a new Case Notification. And then click the Home link, the Summary view does not reflect the latest update.

If we  click any of the Questions link and then click the Home again, this will now display the latest update. Or while in Summary view, we click the Refresh screen in the top right hand menu, it will refresh the the most updated data.

**Comment by scloo** [comment]
Fixed. Forced a refresh of screen before display summary view using Backbone.history.loadUrl()

**Comment by gmcressman** [comment]
Tested and works as expected. Closign.
