### ISSUE TITLE
Changes to completed record has bugs

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#186]
When making changes to a completed record, it validate and gives an error and then quickly return to the record list even though record is not valid. It should stay in the editing mode with the error message.

**Comment by scloo** [comment]
By design (?), if the question has been marked as completed, and you edit a field, it will auto save and redirect back to the summary list.

So, even if the required field is invalid, e.g. blank, the codes checked that if the complete is marked, it will redirect back to the summary list as well. Hence the invalid field value is indirectly accepted.

Question I have is whether we should allow editing once the question has been marked Complete.

**Comment by scloo** [comment]
Fixed the issue by making sure the validation is performed even though the Complete field was originally checked.  
Because the validation has carried out, if there is error in any of the edited field, the Complete field automatically becomes unchecked. That means a previously ticked Completed field has now been moved  to incomplete state. This may pose an issue because the user may have in mind that he/she is editing a completed question, which has now become incomplete. Would not be an issue if user remembers to scroll down to the Completed box and check that.

Needs to revisit the work flow for editing a completed question form.

**Comment by gmcressman** [comment]
I agree that handling edits of question sets that have been marked as Complete is tricky. One possible solution is to handle it as follows:

- If a field value is changed, and the question set is marked as Complete, then mark the question set as not Complete. The user must therefore scroll down and check Complete. 

This is the same procedure that the user followed when the user completed the record previously. It also enables the user to edit multiple fields in the question set, without having to go back and forth between the summary display and the question set display. 

There is another complication: If the user is editing a Household question set, and if the user changes the number of residents in the household, it creates one of the following two situations:

1. If the user increases the number of residents, then the software needs to create a Household Member record for each additional household member.
2. If the user decreases the number of residents, then the user can either delete one of the existing Household Member question sets, or leave it no Complete.

**Comment by scloo** [comment]
During editing of questions set, a previously completed question will be changed to Incomplete state if any of the changed field remains invalid. A snackbar notification will pop up to say that "ALERT: This Form is incomplete" to alert user that the form has moved to Incomplete state.
