### ISSUE TITLE
sync does not show records in democs database

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#187]
After syncing, the new records is still not showing up in the analytics for the democs database.

**Comment by scloo** [comment]
The cron job for UpdateSummaryDocs is running. Even tried manual running of script. But not seeming to update anything. Checked the cases doc on the database and can see the recently sync'ed records in the database.

**Comment by gmcressman** [comment]
New records do appear in the Case Follow-up Report. However, if the app finds that there is more than one record with the same Malaria Case ID, it displays the oldest of those records.

There is still a question concerning whether the view used for dashboard, chart, and map displays is being updated.

**Comment by scloo** [comment]
The problem is partly resolved by running the ResetCaseSummaryDocs script which will recreate the Case Summary docs. However there is still an issue that the script that was started by the cron job isn't working.
The cron job ran this script:
/usr/local/bin/forever start -c /var/www/coconut-analytics/_attachments/node_modules/coffee-script/bin/coffee /var/www/coconut-analytics/_attachments/app/UpdateCaseSummaryDocs.coffee https://cococloud.co/democs

For some reason it isn't detecting changes. Whereas if I were to run the script manually it works fine, and will detect the change and update the Case summary docs.

**Comment by scloo** [comment]
@mikeymckay if I ran the script manually as:
/var/www/coconut-analytics/_attachments/node_modules/coffee-script/bin/coffee /var/www/coconut-analytics/_attachments/app/UpdateCaseSummaryDocs.coffee https://cococloud.co/democs

It works. However the cronjob runs the script as:
/usr/local/bin/forever start -c /var/www/coconut-analytics/_attachments/node_modules/coffee-script/bin/coffee /var/www/coconut-analytics/_attachments/app/UpdateCaseSummaryDocs.coffee https://cococloud.co/democs

which is showing up in the processes as:
/usr/bin/nodejs /usr/local/lib/node_modules/forever/bin/monitor /var/www/coconut-analytics/_attachments/app/UpdatCaseSummaryDocs.coffee

I'm not familiar with the differences between the two.Especially the wrapping via forever.
Perhaps you can spot straight away what the problem here is.

**Comment by scloo** [comment]
@mikeymckay As pointed out the script in the cron job is not working when it is run with 'forever'. And running the script manually works fine. So right now, I just ran the script manually and keep it running in the background using nohup. It's working fine. 
Do you see any reason why I should not change the cron job to use 'nohup' instead of 'forever'?

**Comment by mikeymckay** [comment]
Forever has the benefit of being able to restart the script when something stops. It would probably be worth trying to figure out why that isn't working. However, for our demo app, nohup is fine. I would probably kill it and restart it once a day just to be safe.

**Comment by scloo** [comment]
As of date, the UpdateCaseSummaryDoc script appears to be working fine, tested under Zanzibar environment.

**Comment by gmcressman** [comment]
Fixed.
