### ISSUE TITLE
Username field on loginbox acts strange

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-mobile#193]
Seems like some javascript moves the cursor to the end on keyup or something

**Comment by scloo** [comment]
I don't see this on my end.

**Comment by mikeymckay** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/12015/31178180-ef194b62-a920-11e7-94a1-0a538d1d88cc.gif)

**Comment by mikeymckay** [comment]
Strange.

**Comment by scloo** [comment]
Issue fixed. Removed the onKeyUp js handler. Redundant anyhow.
