### ISSUE TITLE
ResultView showing blank rows

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#196]
In the result table, even though it is showing the correct number of rows, but each row is blank.
![ScreenShot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571a5f9b500b7b0e00eca657/125516c66e82c728ace21e0d46db978826878d9a87e6ab01e81fe086264c22703d46f96925d2b27fba167854590c18a4460a0c16fcf98b28f0b33426984019af80330b2b9b645bf9fa9015ad03bb2a8a4a85beb58f49c6ec342ce4829d02.png)

**Comment by scloo** [comment]
Upon tracing, console error shows null values for each of the attributes, the FacilityName and MalariaCaseID.
![ScreenShot2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571a5f9b500b7b0e00eca657/125516c66e82c728ace21e0d46db978826878d9a87e6ab11e611b2843b492d762a10e17132d0b479e8472f025a591dfa495f0d17aef98929a5e03978dc4e17ff933c0120996048e6edc00db513bb27814e80b6b48349c5ef3f2de783885d73.png)

**Comment by scloo** [comment]
@mikeymckay 
I traced the source of the issue to the following section of codes: (ResultCollection.coffee: 23)

Coconut.database.query "results", queryOptions,
      (error,result) =>
        @results = _(result.rows).map (row) ->
          returnVal = _.object(fields,row.value)
          returnVal._id = row.id
          new Result(returnVal)
        options.success()

The reason the FacilityName and the MalariaCaseID are always null is because in the code above, row.value is always null as shown in the data below. Not sure where the value for  row.value comes from.


Sample value of row in codes above:

{key: Array(3), id: "result-case_notification-KxJKmRA-KxJKcUi", value: Array(2), doc: {…}}
doc: {question: "Case Notification", collection: "result", createdAt: "2017-10-25T12:21:58-04:00", lastModifiedAt: "2017-10-25T12:22:11-04:00", user: "mmckay", …}
id: "result-case_notification-KxJKmRA-KxJKcUi"
key: (3) ["Case Notification", false, "2017-10-25T12:21:58-04:00"]
value: (2) [null, null]
__proto__: Object

**Comment by mikeymckay** [comment]
Was this a result that you created? I have just committed a fix (hack) to keep all of the newly created data in the same format as the old data. This might solve the issue.

**Comment by scloo** [comment]
Yes, this is a result I created. I have just pulled the latest commit. I deleted and reinstall the database locally.  And the cases are still not showing.

**Comment by mikeymckay** [comment]
Make sure you pull the plugin and update that also.

**Comment by scloo** [comment]
I forgot to pull the plugin.  I just did a moment ago and I noticed that you have removed updatePluginBundle.sh from the repos. Is there a reason for that? Is there a new way to push the plugin to couchdb?

**Comment by scloo** [comment]
Hmm... have to do it a few times. Now it is showing. I need to know what I did differently this time. Maybe I deleted all the cookies and cache...

**Comment by scloo** [comment]
Issue fixed
