### ISSUE TITLE
When user clicks on Complete, display does not automatically scroll to reveal the first error at the top of the display.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#24]

**Comment by gmcressman** [comment]
Alternative approach suggested by Steve: Display an error message at the bottom, calling the user's attention to errors above. I favor scrolling to the first error if possible.

**Comment by gmcressman** [comment]
This is still a usability issue. If errors are found when Complete is checked, they may be off the display.

**Comment by mikeymckay** [comment]
It now scrolls. Error was happening because scrollbar is on a div not on the body of the app. Scrolling position isn't perfect, needs to be tested and tweaked for question sets with more questions.

**Comment by mikeymckay** [comment]
Scrolling is crazy. Turning off and reopening.

**Comment by mikeymckay** [comment]
Fixed the crazy.

**Comment by gmcressman** [comment]
This works great! Two suggestions:


1.       Error messages and Next Error button are very small – too small on my Nexus 7. Can they be scaled larger?

2.       Pressing Next Error on the last error automatically submits the record and opens a new record. That’s very efficient, but the user may not understand what has happened. If, on pressing Next Error, there are no more errors, I suggest scrolling to the bottom  so the user can press on Complete.


-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>
