### ISSUE TITLE
Create new instance on Ubuntu 14.04

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-mobile#31]
Currently on coreos, which reboots and doesn't restart without explanation.

**Comment by scloo** [comment]
New instance created on Netmagic. 
Changed default root password give by Netmagic.
Delete initial user account given.
Added public keys to root authorized_keys file.
Enabled root to ssh in without password.
Upgrade Ubuntu from 12.04 to 14.04
Created server.key
Created Certificate Signing Request for RAPIDSSL.

**Comment by gmcressman** [comment]
Install km.cococloud.co on this instance. Once it's up and running this issue can be closed.

**Comment by scloo** [comment]
km.cococloud.co is now pointing to server
