### ISSUE TITLE
Change all user names to lower-case. Make usernames case in-sensitive.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#35]
Mike, can we have a config option to make usernames case-insensitive?

**Comment by mikeymckay** [comment]
The way I do it in Zim is just force all characters typed in the username box to upcase immediately. That's possible.

**Comment by scloo** [comment]
Looks like the user names have been changed to lower case. Mike must have beaten me to it.

**Comment by scloo** [comment]
Mike, forcing the characters to upcase, is this only in the user login area? The reason I ask is that all the usernames are now in lower cases. I assume when you authenticate, you convert that to lower case for comparison.

**Comment by mikeymckay** [comment]
@scloo right - I mentioned uppercase because that's how I did it before, but I agree, here it would have to force lowercase. As long as android doesn't automatically capitalize the first letter then I think we can leave this for later. Can somebody test this for me?

**Comment by mikeymckay** [comment]
On Android the first letter is automatically capitalized, so would be good to force a downcase on keypress.

**Comment by mikeymckay** [comment]
Nice simple solution for this:

style="text-transform:lowercase;" on keyup="javascript:this.value=this.value.toLowerCase();

**Comment by gmcressman** [comment]
That looks like a great solution to this.
