### ISSUE TITLE
Enable database reset during failure

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-mobile#38]
With old version of app I synced this morning, but then the app wouldn't load and couldn't do anything. Need to be able to recover from this.

Some failure handling code that exists outside of app will probably be necessary.

**Comment by gmcressman** [comment]
Ugh. I doubt that money can do this, but @sloo would know.

-gmc (from iPhone)

On Aug 20, 2015, at 4:37 AM, Mike McKay <notifications@github.com<mailto:notifications@github.com>> wrote:


With old version of app I synced this morning, but then the app wouldn't load and couldn't do anything. Need to be able to recover from this.

Some failure handling code that exists outside of app will probably be necessary.

-

**Comment by mikeymckay** [comment]
This was failing due to an old way of looking up default configuration values. Fixed now.

**Comment by scloo** [comment]
How do we detect this from outside the app, if necessary? I think Gordon has in mind to to use Monit. But that requires some way to know when to reset the database.

**Comment by mikeymckay** [comment]
No - sorry I sent you guys down the wrong path. There was a problem *on the
client* whereby if there is a javascript failure before the routing code is
running then it won't be able to get to the code that enables a database
reset. I don't think is an issue now, as my problem was caused by something
else.
