### ISSUE TITLE
Form not showing check boxes for diagnosis in Admin

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#47]
In the Admin app, when opening New Visit, there is no checkbox options under the Provisional Diagnosis. Likewise when you open any of the existing form data.

**Comment by mikeymckay** [comment]
Are you talking about on the server? That whole UI will be disable. See #46.

**Comment by scloo** [comment]
Yes, I was referring to the new server, with the link you just provided.

**Comment by mikeymckay** [comment]
Ok, closing - the server side UI needs the same treatment as the client - but mostly with everything removed.
