### ISSUE TITLE
Last sync status on fly-out panel may not be correct

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#51]
Synced repeatedly without errors. Status of last sync in panel still says FAILED. Examples:

![2015-08-21_15-35-29](https://cloud.githubusercontent.com/assets/329768/9417629/f002c804-481b-11e5-90e6-fa1708a61550.png)

![2015-08-21_15-36-20](https://cloud.githubusercontent.com/assets/329768/9417645/00eeeaa8-481c-11e5-9369-64edd577e1f3.png)

**Comment by mikeymckay** [comment]
Yeah this is a bug
