### ISSUE TITLE
Mobile UI: Improve MD on delete record confirmation

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#54]
Not urgent, but "Yes Cancel" are much smaller than the question on the delete record confirmation dialogue, making them more difficult to see. Some work needs to be done on the MD here.

![style_2015-08-21_17-11-38](https://cloud.githubusercontent.com/assets/329768/9419249/2b0e4232-4828-11e5-89ad-09100f9520a8.png)

**Comment by scloo** [comment]
Issue addressed.
