### ISSUE TITLE
Change encryption key to be downloaded securely from server

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-mobile#61]
This is @ckelley's idea to get rid of the weirdness around using usernames/passwords. It will solve all of our strange scenarios.

**Comment by mikeymckay** [comment]
Problem: requires you to be online. In offline mode how would you decrypt the database?

**Comment by gmcressman** [comment]
Cache locally? Update during sync? How could the key be stored securely locally? Insecure key storage is as common encryption weakness, isn't it?

**Comment by mikeymckay** [comment]
Encyrption key is stored in a database encrypted with the user's password. So only a valid user can get the required encryption key.
