### ISSUE TITLE
IsValid error in Gender; TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#62]
To reproduce:
Add Visit.
Do not select a Gender. 
Click on Complete.

**Comment by mikeymckay** [comment]
This is all fixed. Forgot to deploy.

**Comment by gmcressman** [comment]
Synced, Retested. Error is still there. Shutdown and restarted the app. Synched. Retested Error is still there. I still must not have the fix on my device.

**Comment by scloo** [comment]
I have the same error. Did the RESET ALL, clear all data locally.

**Comment by gmcressman** [comment]
Tested and verified.
