### ISSUE TITLE
Update forms for material design

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-mobile#63]
This will require updating Coconut Mobile's handling of form types that haven't yet been migrated to Material Design (Autocomplete, location).

**Comment by mikeymckay** [comment]
Have replaced typeahead.js with awesomplete, but more work to be done...

**Comment by mikeymckay** [comment]
Autocomplete looks good. Location requires some more styling still.

**Comment by gmcressman** [comment]
Done.
