### ISSUE TITLE
Question names overflow past the Sync button

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#68]
Where this is more than 2 question sets on the header, it becomes like this:

![screen shot 2015-12-04 at 10 31 47 am](https://cloud.githubusercontent.com/assets/8493786/11593419/48ed1624-9a72-11e5-8703-c8131ed6f5e8.png)

**Comment by gmcressman** [comment]
We cannot use the vertical ellipsis after each question set. We need to use it on the far right to display a pop-up menu of question sets that cannot be displayed in the header. We could use the name of each question set as the link to the records. Other ideas?

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by scloo** [comment]
I believe this has been resolved.

**Comment by gmcressman** [comment]
Fixed. It can occur in some circumstances, but this appears to be rare, and minor.
