### ISSUE TITLE
Detect https when setting up new app

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-mobile#70]
Currently if you are on the https url and try and setup a new app without specifying https, it will default to http and fail for security reasons.

**Comment by gmcressman** [comment]
Please check on this.

**Comment by scloo** [comment]
Looks like this has been fixed. Tried http://cococloud.co or cococloud.co , they both work fine. I believe we added a checking that if cloud and http, it will swap for https. If localhost, it stays http.
