### ISSUE TITLE
Require HTTPS for all data transmissions with the cococloud server

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#85]
- [ ] Do not fall back to HTTP for data transmission.
- [ ] If HTTPS cannot be used for any reason, log and report the error to the user, and suggest how to correct the problem.

**Comment by gmcressman** [comment]
Has this been completed?

**Comment by scloo** [comment]
By default, if you use HTTP it will be auto direct to HTTPS automatically. So accessing Coconut Mobile is only via https://mobile.cococloud.co/

**Comment by gmcressman** [comment]
Confirmed. Closed.
