### ISSUE TITLE
Mobile UI: Analytics display for user

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile#98]
- [x] Display selected statistics on the "home" display
- [x] Style is consistent with MD and the Analytics app
- [x] Provide and obvious way for users to return to this display.

**Comment by gmcressman** [comment]
This should become the "Home" display for the Mobile app.

**Comment by gmcressman** [comment]
Use the MD "home" icon for this on the menu. Use "Home" when display width permits display of the menu text.

**Comment by scloo** [comment]
Done
